# Python Riddles

In [1]:
# all necessary imports
import numpy as np

Give a sum of all odd numbers from 1 to 100 inclusive. (one-liner)
<< 1/5 >>

In [2]:
sum([i for i in range(1,101) if i%2==1])

2500

Sum all integers within the range `i = 1…1000` inclusive. If the number `i` is a multiple of 3 or 5, double it and add it to the sum. (one-liner) << 2/5 >>

In [3]:
sum([2*i for i in range(1,1001) if i%3==0 or i%5==0]) + sum([i for i in range(1,1001) if not i%3==0 and not i%5==0])

734668

Try to find maximum value of pair over given lists (you can't use numpy!) (one-liner). << 3/5 >>

```
a = [3, 1, 5, 3, 4, 7, 8,  11]
b = [0, 2, 2, 0, 4, 9, 99, 10]
```

In [4]:
a = [3, 1, 5, 3, 4, 7, 8,  11]
b = [0, 2, 2, 0, 4, 9, 99, 10]
list(map(lambda pair: max(pair), zip(a, b)))

[3, 2, 5, 3, 4, 9, 99, 11]

Assign to a, b, c three multiples of 17 from range 100 to 150. (one-liner) << 1/5 >>

In [5]:
a, b, c = [i for i in range(100,150) if i%17==0]

Print each char as many times as given value in alphabetical order. (one-liner) << 1/5 >>
```
m = {'a': 1,  'c': 3, 'b': 2, 'd': 4}
```

In [6]:
m = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
for k,v in sorted(m.items()): print(k*v)

a
bb
ccc
dddd


Seprate int from chars in `[(1, 'a'), (2, 'b'), (3, 'c')]`. (one-liner) << 4/5 >>

In [7]:
x = [(1, 'a'), (2, 'b'), (3, 'c')]
list(zip(*x))

[(1, 2, 3), ('a', 'b', 'c')]

Invert given dictionary: (one-liner) << 2/5 >>
```
d = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
```

In [8]:
d = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
{d[k]:k for k in d}

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}

Write a lambda function to group `k` adjacent list items together. (one-liner) << 5/5 >>

You may test it on:
```
a = [1, 2, 3, 4, 5, 6]
```

In [9]:
a = [1, 2, 3, 4, 5, 6]
group = lambda a, k: list(zip(*([iter(a)] * k)))
group(a, 2)

[(1, 2), (3, 4), (5, 6)]

Flatten a list of lists `[[1, 2], [3, 4], [5, 6]]`. (one-liner) << 3/5 >>

In [10]:
a = [[1, 2], [3, 4], [5, 6]]
sum(a, [])

[1, 2, 3, 4, 5, 6]

Write a function writing to terminal histogram of given numbers. For example for numbers `[3, 6, 4]` it should look like:
```
***
******
****
```
(2/3 lines) << 1/5 >>

In [11]:
def txthist(x):
    for i in x: print('*'*i)

txthist([3, 6, 4])

***
******
****


Print every second letter from a string `a` in reversed order. (one-liner) << 2/5 >>

In [12]:
a = "abcdefghij"
a[::2][::-1]

'igeca'

Exchange every "a" letter in string with "duck". (one-liner) << 1/5 >>

In [13]:
a = "annapurna"
"".join(["duck" if i=="a" else i for i in a])
"duck".join(a.split("a"))

'ducknnduckpurnduck'

Print letter as many times as the number on its right says for string : `a3,f8,g1,h7,o2`. (one-liner)
e.g. for `a2,b5` result should be:
```
aa
bbbbb
```
<< 2/5 >>

In [14]:
for x in 'a3,f8,g1,h7,o2'.split(","): print(x[0]*int(x[1]))

aaa
ffffffff
g
hhhhhhh
oo


# Numpy

Choose all non nan elements from array x. (oneliner)
```
x = np.array([243, np.nan, 123, np.nan, np.nan ,6])
```

<< 3/5 >>

In [15]:
x = np.array([243, np.nan, 123, np.nan, np.nan ,6])
x[~np.isnan(x)]

array([ 243.,  123.,    6.])

Write function which exchange values o binary ones depending on threshold. Test it on `np.random.random(10)` array. (2/3 lines)

<< 2/5 >>

In [16]:
z = np.random.random(10)

def f(z, threshold=0.5):
    z[np.where(z>threshold)[0]]=1
    z[np.where(z<=threshold)[0]]=0

f(z)
print(z)

[ 0.  0.  1.  0.  1.  0.  0.  0.  0.  0.]


Mulitply an array of dimension (5,5,3) by an array with dimensions (5,5). (one-liner)

<< 2/5 >>

In [17]:
A = np.ones((5,5,2))
B = 2*np.ones((5,5))
A * B[:,:,None]

array([[[ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.]],

       [[ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.]],

       [[ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.]],

       [[ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.]],

       [[ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.]]])

Change the sign of a float inplace (one-liner)

<< 1/5 >>

In [18]:
arr = np.random.uniform(-1.0,1.0,5)
np.negative(arr, out=arr)

array([-0.2009929 ,  0.86279509,  0.98360998, -0.09917452, -0.77284729])

Create matrix in shape 3x4 with values ranging from 0 to 12 (one-liner)

<< 1/5 >>

In [19]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Find indices of non-zero elements from:
```
a = [1, 2, 0, 4, 0, 5]
```
(one-liner)

<< 1/5 >>

In [20]:
a = [1, 2, 0, 4, 0, 5]
np.nonzero(a)[0]

array([0, 1, 3, 5], dtype=int64)

Make an array immutable (read-only) (one-liner)

<< 2/5 >>

In [23]:
X = np.zeros(10)
X.flags.writeable = False
#X[0] = 1

Replace all maximum numbers from 3x3 matrix with integers from 0 to 10 with -10 (one-liner)

<< 2/5 >>

In [22]:
Z = np.random.randint(10, size=(3,3))
Z[np.where(Z==Z.max())]=-10
Z

array([[-10,   8,   4],
       [  3,   5,   1],
       [  6,   4,   1]])